# Generated by Django 5.1.3 on 2024-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0003_alter_voter_precinct_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="voter",
            name="street_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="voter",
            name="zip_code",
            field=models.CharField(max_length=20),
        ),
    ]
